name: Build and Test

on:
  # Run when pushing to stable branches
  push:
    branches:
    - 'master'
  # Run on branch/tag creation
  create:
  # Run on pull requests
  pull_request:

jobs:
  test-coverage:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir_version:
        - 1.8.2
        - 1.9.4
        - 1.10.2
        otp_version:
        - 21.3.8.14
        - 22.3
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
    - uses: actions/cache@v1
      with:
        path: _build
        key: ${{ runner.os }}-_build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-_build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ github.sha }}
    - uses: erlef/setup-elixir@v1.6.0
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: ${{ matrix.elixir_version }}
    - name: Install Dependencies
      run: mix deps.get
    - name: Check formatting
      run: mix format --check-formatted
    - name: Compile
      run: mix compile
    - name: Test and Coverage
      run: mix coveralls.json -o coverage_results
    - name: Upload Coverage Results to CodeCov
      run: |
        bash <(curl -s https://codecov.io/bash)
